### ISSUE TITLE
support for javascript, not only for typescript

### ISSUE THREAD

**Issue by jet10000** [nateshmbhat/svelte-ace#1]
I test it, but only for typescript

**Comment by nateshmbhat** [comment]
Hi can u tell me whats the error?
I will fix it asap.

**Comment by nateshmbhat** [comment]
closing until response.

**Comment by dit7ya** [comment]
I tried the example given in the readme in a JS project and received the following 

`Failed to resolve import "brace/mode/json" from "src/lib/..."`

Perhaps provide a complete JS example?
