### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by glitchedgitz** [nateshmbhat/svelte-ace#12]
![image](https://user-images.githubusercontent.com/58145476/188661522-39453529-49e5-4c4b-9dd4-581725101c6d.png)

**Comment by nateshmbhat** [comment]
Not sure what's the issue. Right now occupied with other stuff so not getting time to look into this. Feel free to raise a PR.... 🙏

**Comment by glitchedgitz** [comment]
Well, I am new to svelte and just want to test ace-editor.
I check the svelte typescript project, it's working in it.

Any idea how to run it in only JS projects?

**Comment by winstonzhao** [comment]
@glitchedgitz  You didn't have typescript installed.
